/**
 * LessonCoordinator — the one place the asynchronous chain lives.
 *
 *   lessonRequested / siteSelected
 *        -> LessonPlanner (Gemini)
 *        -> LessonValidator
 *        -> LessonEngine.loadLesson()
 *
 * WHY THIS IS NOT IN THE ENGINE. LessonEngine is a deterministic state machine
 * that is testable from fixtures precisely because it calls nothing: it emits
 * `lessonRequested` and forgets. Putting the Gemini call inside it would make
 * every engine test depend on the network and on the model's mood. So the
 * engine asks, this coordinates, and the engine is fed a finished plan through
 * its ordinary public entry point — the same one a fixture uses.
 *
 * Everything that can go wrong is handled HERE, and all of it is visible:
 *
 *   - a second request while one is in flight  -> ignored, user told, no second call
 *   - "stop" while compiling                   -> aborted, and a late response
 *                                                 cannot resurrect the lesson
 *   - network / gateway / token failure        -> ONE automatic retry, then a
 *                                                 friendly error, then IDLE
 *   - a response that never arrives            -> watchdog, treated as network
 *   - hard validation failure                  -> error state, engine untouched,
 *                                                 raw response logged as a fixture
 *
 * ## The generation counter is the whole cancellation story
 *
 * Promises cannot be cancelled. `requestId` increments on every new request AND
 * on every abort; each resolution checks the id it was issued under and drops
 * itself if the world has moved on. Without it, a cancelled request quietly
 * finishes 8 s later and loads a lesson the user has already dismissed — the
 * worst class of bug on stage, because it looks like the Lens acting on its own.
 */
import { eventBus, Events } from "./EventBus";
import { LessonEngine } from "./LessonEngine";
import { LessonRequestOutcome, requestLesson, requestNextStep } from "./LessonPlanner";
import { LessonAnchorPayload, LessonRequestFailure, MenuSelectedPayload, RequestStatePayload } from "./RequestTypes";
import { describeDegradations } from "./LessonValidator";
import { gatewayDropPending, gatewayStatus, GW_BACKGROUND } from "./GatewayQueue";
import { XYZ } from "./SurveyTypes";

@component
export class LessonCoordinator extends BaseScriptComponent {
  @ui.separator
  @ui.label('<span style="color: #7CFFB2;">Wiring</span>')

  @input
  @hint("Systems/LessonEngine. The coordinator feeds it finished plans; the engine never calls out.")
  private engine: LessonEngine;

  @input
  @hint("Assets/AI/prompts.generated.json — built from the .txt sources by Tools/build-prompts.py")
  private promptsAsset: JsonAsset;

  @ui.separator
  @ui.label('<span style="color: #7CFFB2;">Marker shortcuts</span>')
  @ui.label('<span style="color: #94A3B8; font-size: 11px;">Tapping a site marker SPEAKS one of these. It is a shortcut for talking, not a fixture: the plan is generated by Gemini exactly as if the words had been said out loud.</span>')

  @input private tentPhrase: string = "help me pitch a tent";
  @input private firePhrase: string = "help me build a campfire";

  @ui.separator
  @ui.label('<span style="color: #7CFFB2;">Menu shortcuts</span>')
  @ui.label('<span style="color: #94A3B8; font-size: 11px;">Main-menu rows 2-5 are the same trick as a marker tap: a fixed phrase through the SAME generative lesson path. No fixtures, no special-casing.</span>')

  @input private waterPhrase: string = "help me purify water";
  @input private burnPhrase: string = "how do I treat a burn";

  @ui.separator
  @ui.label('<span style="color: #7CFFB2;">Next-step suggestion</span>')
  @ui.label('<span style="color: #94A3B8; font-size: 11px;">A SEPARATE background call fired when a lesson completes — never a field in the lesson plan. Putting it in the lesson schema shifted lesson structure and was reverted; a second call cannot perturb the first one\'s output.</span>')

  @input
  @hint("Ask for a next-step suggestion when a lesson completes. Off = the completion card never gains a next line, and no extra call is made.")
  private suggestNextStep: boolean = true;

  @input
  @widget(new SliderWidget(16, 200, 1))
  @hint("Output cap for the suggestion. Deliberately far above six words: a cap tight enough to truncate is a worse bug than a long answer (see the 'If' incident in LessonPlanner).")
  private nextStepMaxTokens: number = 60;

  @ui.separator
  @ui.label('<span style="color: #7CFFB2;">Failure handling</span>')

  @input
  @widget(new SliderWidget(5, 60, 1))
  @hint("Give up on a response after this long and treat it as a network failure. A request that never resolves would otherwise leave the HUD compiling forever.")
  private requestTimeoutSec: number = 25;

  @input
  @widget(new SliderWidget(0, 5, 0.1))
  @hint("Pause before the single automatic retry.")
  private retryDelaySec: number = 0.6;

  @input
  @widget(new SliderWidget(0, 60, 1))
  @hint("Extra grace while a request waits for the gateway slot. Requests are strictly one at a time, so a lesson asked for mid-synthesis waits for that call to finish. The real timeout re-arms at dispatch; this only stops a request stuck BEHIND something from hanging forever.")
  private slotWaitAllowanceSec: number = 45;

  @input
  @widget(new SliderWidget(1, 15, 0.5))
  @hint("How long the error state stays on screen before returning to IDLE.")
  private errorHoldSec: number = 5;

  @input
  @hint("Log the full raw envelope of a failed response as a FIXTURE| line, so it can be lifted straight out of the log into Assets/AI/fixtures (hard rule 5).")
  private dumpFailedResponses: boolean = true;

  @input private enableLogging: boolean = true;

  // ------------------------------------------------------------------ state

  private state: "IDLE" | "COMPILING" | "ERROR" = "IDLE";
  /** Generation counter. See the header note — this is the cancellation. */
  private requestId: number = 0;
  private activeText: string = "";
  private activeSource: string = "";
  private activeAnchor: XYZ | null = null;
  private attempt: number = 0;
  private startedAtSec: number = 0;
  private systemPrompt: string = "";
  private nextStepPrompt: string = "";
  /**
   * Generation counter for the suggestion, exactly like requestId is for a
   * lesson: it moves on every completion AND on every new user request, so a
   * suggestion that lands after the user has moved on drops itself instead of
   * putting a stale line on a card that has already gone.
   */
  private suggestionId: number = 0;

  private watchdog: DelayedCallbackEvent;
  private retryTimer: DelayedCallbackEvent;
  private errorTimer: DelayedCallbackEvent;

  onAwake(): void {
    this.watchdog = this.createEvent("DelayedCallbackEvent");
    this.watchdog.bind(() => this.onWatchdog());
    this.watchdog.enabled = false;

    this.retryTimer = this.createEvent("DelayedCallbackEvent");
    this.retryTimer.bind(() => this.issue());
    this.retryTimer.enabled = false;

    this.errorTimer = this.createEvent("DelayedCallbackEvent");
    this.errorTimer.bind(() => this.toIdle());
    this.errorTimer.enabled = false;

    this.createEvent("OnStartEvent").bind(() => this.onStart());
  }

  private log(msg: string): void {
    if (this.enableLogging) print("[COORD] " + msg);
  }

  private onStart(): void {
    this.systemPrompt = this.loadPrompt("lesson");
    this.nextStepPrompt = this.loadPrompt("nextStep");

    // A finished lesson is the only thing that asks for a suggestion, and it
    // asks in the background while the user reads the completion card.
    eventBus.subscribe(
      Events.lessonCompleted,
      (p: { title: string; steps: number; nextSuggestion?: string; finalStep?: string }) =>
        this.askNextStep(p)
    );

    eventBus.subscribe(Events.lessonRequested, (p: { text: string }) => {
      this.request(p ? p.text : "", null, "voice");
    });

    // A marker tap is a spoken phrase with a place attached. Same path, same
    // Gemini call, same validator — the only difference is that the ground
    // content knows where to stand.
    eventBus.subscribe(
      Events.siteSelected,
      (p: { kind: string; slot: string; position: XYZ }) => {
        if (!p) return;
        const phrase = p.kind === "fire" ? this.firePhrase : this.tentPhrase;
        this.log("marker " + p.slot + " (" + p.kind + ') -> "' + phrase + '"');
        this.request(phrase, p.position, "marker");
      }
    );

    // Menu rows 2-5 — the marker trick again: a fixed phrase, spoken by proxy,
    // through the same Gemini path. Row 1 (survey) and row 6 (navigate) have
    // other owners and are ignored here. No anchor: the lesson stands where
    // the design-time zone default puts it.
    eventBus.subscribe(Events.menuSelected, (p: MenuSelectedPayload) => {
      if (!p) return;
      const phrase =
        p.row === 2 ? this.tentPhrase :
        p.row === 3 ? this.firePhrase :
        p.row === 4 ? this.waterPhrase :
        p.row === 5 ? this.burnPhrase : "";
      if (phrase.length === 0) return;
      this.log("menu row " + p.row + " (" + p.source + ') -> "' + phrase + '"');
      this.request(phrase, null, "menu");
    });

    eventBus.subscribe(Events.stopRequested, () => {
      if (this.state === "COMPILING") this.abort("cancelled", "REQUEST CANCELLED");
    });

    this.emitState("IDLE", "", "", 0);
    this.log(
      "ready. timeout=" + this.requestTimeoutSec + "s retryDelay=" + this.retryDelaySec +
        "s prompt=" + this.systemPrompt.length + " chars"
    );
  }

  private loadPrompt(key: string): string {
    if (!this.promptsAsset) {
      this.log("FAIL: promptsAsset not wired — every request will fail");
      return "";
    }
    try {
      const value = JSON.parse(this.promptsAsset.getString())[key];
      return typeof value === "string" ? value : "";
    } catch (e) {
      this.log("FAIL: could not read prompts asset: " + e);
      return "";
    }
  }

  /**
   * Fire-and-forget suggestion request. Everything about it is allowed to fail
   * quietly: the card renders with no next line and the lesson is unaffected.
   */
  private askNextStep(p: { title: string; nextSuggestion?: string; finalStep?: string }): void {
    this.suggestionId++;
    const id = this.suggestionId;

    if (!this.suggestNextStep || this.nextStepPrompt.length === 0) return;
    // A plan that already carries one (the dormant schema path) needs no call.
    if (p && p.nextSuggestion && p.nextSuggestion.length > 0) return;

    requestNextStep(
      p ? p.title : "",
      p && p.finalStep ? p.finalStep : "",
      this.nextStepPrompt,
      this.nextStepMaxTokens
    ).then((outcome) => {
      if (id !== this.suggestionId) {
        this.log("dropping stale next-step suggestion (#" + id + " of #" + this.suggestionId + ")");
        return;
      }
      if (outcome.text.length > 0) {
        this.log('next step in ' + outcome.latencyMs + 'ms: "' + outcome.text + '"');
      } else {
        this.log(
          "no next step (" + (outcome.dropped ? "dropped for a user request" : outcome.error || "none offered") + ")"
        );
      }
      eventBus.emit(Events.nextStepSuggested, {
        text: outcome.text,
        latencyMs: outcome.latencyMs,
        reason: outcome.dropped ? "dropped" : outcome.error,
      });
    });
  }

  // --------------------------------------------------------------- requests

  /**
   * THE entry point. Public so a diagnostic can drive it without faking an
   * event, and so a future feature (a suggestion chip, a repeat button) has an
   * honest way in.
   */
  public request(text: string, anchor: XYZ | null, source: string): void {
    const clean = (text || "").trim();
    if (clean.length === 0) return;

    if (this.state === "COMPILING") {
      // Deliberately NOT queued. A queue means the user waits 12 s for the
      // answer to a question they have already moved on from, and it doubles
      // the token spend for a request nobody is still watching.
      this.log('BUSY: ignoring "' + clean + '" — still compiling "' + this.activeText + '"');
      this.emitState("BUSY", this.activeText, "ONE AT A TIME — STILL WORKING", this.attempt);
      return;
    }

    // An error on screen is stale the moment the user asks for something new.
    this.errorTimer.enabled = false;

    // Clear queued background synthesis out of the way. Requests are strictly
    // one at a time now, so a pile of prefetches ahead of this one is a pile of
    // seconds the user spends staring at COMPILING. The in-flight call cannot
    // be cancelled; everything merely waiting can.
    const dropped = gatewayDropPending(GW_BACKGROUND, "user asked for a lesson");
    if (dropped > 0) this.log("cleared " + dropped + " queued background call(s) — " + gatewayStatus());

    // A user request also retires any suggestion in flight — its card is gone.
    this.suggestionId++;
    this.requestId++;
    this.activeText = clean;
    this.activeSource = source;
    this.activeAnchor = anchor;
    this.attempt = 1;
    this.startedAtSec = getTime();
    this.state = "COMPILING";

    this.log('request #' + this.requestId + ' "' + clean + '" via ' + source + (anchor ? " anchored" : ""));
    this.emitState("COMPILING", clean, "", 1);
    this.issue();
  }

  /** Fires the actual call for the current attempt. */
  private issue(): void {
    this.retryTimer.enabled = false;
    const id = this.requestId;
    const attempt = this.attempt;

    // Armed generously until dispatch, then re-armed tight. See slotWaitAllowanceSec.
    this.watchdog.enabled = true;
    this.watchdog.reset(this.requestTimeoutSec + this.slotWaitAllowanceSec);

    requestLesson(this.activeText, this.systemPrompt, (queuedMs) => {
      if (id !== this.requestId) return;
      this.watchdog.enabled = true;
      this.watchdog.reset(this.requestTimeoutSec);
      if (queuedMs > 50) this.log("request #" + id + " waited " + queuedMs + "ms for the gateway slot");
    }).then((outcome) => {
      this.handleOutcome(outcome, id, attempt);
    });
  }

  /**
   * The single place a response is turned into an outcome for the user.
   *
   * Public and id-checked on purpose: this is the fixture seam. A diagnostic
   * can hand it a stored envelope and exercise the real failure handling —
   * logging, error state, engine survival — with no network in the loop
   * (hard rule 5). Live and test go through the same door.
   */
  public handleOutcome(outcome: LessonRequestOutcome, id: number, attempt: number): void {
    if (id !== this.requestId) {
      this.log("dropping response for stale request #" + id + " (current #" + this.requestId + ")");
      return;
    }
    if (this.state !== "COMPILING") {
      this.log("dropping response for #" + id + " — no longer compiling");
      return;
    }

    this.watchdog.enabled = false;
    const elapsed = Math.round((getTime() - this.startedAtSec) * 1000);
    const v = outcome.validation;

    // --- transport: retry once, then give up visibly --------------------
    if (outcome.transportError) {
      this.log("attempt " + attempt + " transport failure after " + elapsed + "ms: " + v.summary);
      this.dumpFixture(outcome, "transport");
      if (attempt < 2) {
        this.attempt = 2;
        this.emitState("COMPILING", this.activeText, "CONNECTION LOST — RETRYING", 2);
        this.retryTimer.enabled = true;
        this.retryTimer.reset(this.retryDelaySec);
        return;
      }
      this.fail("network", "GUIDE LINK DOWN — CHECK CONNECTION");
      return;
    }

    // --- validation: the model answered, and the answer is unusable ------
    if (!v.ok) {
      this.log("validation FAILED after " + elapsed + "ms: " + v.summary);
      for (let i = 0; i < v.issues.length; i++) {
        this.log("  issue " + v.issues[i].code + " at " + v.issues[i].path + ": " + v.issues[i].message);
      }
      this.dumpFixture(outcome, "invalid");
      // No retry: the model produced a real answer, it is just the wrong shape.
      // Another 12 s at temperature 0 buys the same answer again.
      this.fail("validation", "GUIDE RESPONSE UNREADABLE — SAY IT AGAIN");
      return;
    }

    // --- success ---------------------------------------------------------
    if (v.degradations.length > 0) {
      this.log(
        "DEGRADED x" + v.degradations.length + " — " + describeDegradations(v.degradations)
      );
    }
    this.log(
      'lesson ready in ' + elapsed + 'ms (gateway ' + outcome.latencyMs + 'ms, queued ' +
        outcome.queuedMs + 'ms): "' + v.plan.title + '" ' + v.plan.steps.length +
        " steps, " + v.degradations.length + " degraded"
    );

    this.state = "IDLE";
    this.emitState("IDLE", "", "", attempt);

    // Anchor FIRST: loadLesson walks straight into step 0 and announces its
    // companion, so the zone has to know where it stands before that fires.
    const anchor: LessonAnchorPayload = {
      position: this.activeAnchor,
      source: this.activeAnchor ? "site" : "default",
    };
    eventBus.emit(Events.lessonAnchorChanged, anchor);

    if (this.engine) this.engine.loadLesson(v.plan);
    else this.log("FAIL: engine not wired — plan validated but nothing to load it into");
  }

  private onWatchdog(): void {
    if (this.state !== "COMPILING") return;
    this.log("watchdog: no response after " + this.requestTimeoutSec + "s");
    if (this.attempt < 2) {
      this.attempt = 2;
      // Bump the id so the abandoned promise cannot land later and load a
      // lesson on top of the retry's.
      this.requestId++;
      this.emitState("COMPILING", this.activeText, "STILL WAITING — RETRYING", 2);
      this.issue();
      return;
    }
    this.requestId++;
    this.fail("timeout", "GUIDE LINK TIMED OUT — SAY IT AGAIN");
  }

  /** Cancel whatever is in flight. The in-flight promise is orphaned by the id bump. */
  private abort(reason: LessonRequestFailure, message: string): void {
    this.log("abort (" + reason + "): dropping request #" + this.requestId);
    this.requestId++;
    this.watchdog.enabled = false;
    this.retryTimer.enabled = false;
    this.state = "IDLE";
    this.activeText = "";
    this.emitState("IDLE", "", message, 0, reason);
  }

  private fail(reason: LessonRequestFailure, message: string): void {
    this.state = "ERROR";
    this.watchdog.enabled = false;
    this.retryTimer.enabled = false;
    this.emitState("ERROR", this.activeText, message, this.attempt, reason);
    // The engine is untouched by all of this — it never left IDLE — so there
    // is nothing to reset, only a message to retire.
    this.errorTimer.enabled = true;
    this.errorTimer.reset(this.errorHoldSec);
  }

  private toIdle(): void {
    this.errorTimer.enabled = false;
    if (this.state !== "ERROR") return;
    this.state = "IDLE";
    this.activeText = "";
    this.emitState("IDLE", "", "", 0);
  }

  private emitState(
    state: "IDLE" | "COMPILING" | "BUSY" | "ERROR",
    requestText: string,
    message: string,
    attempt: number,
    reason?: LessonRequestFailure
  ): void {
    const payload: RequestStatePayload = {
      state: state,
      requestText: requestText,
      message: message,
      attempt: attempt,
      reason: reason ? reason : "",
      source: this.activeSource,
    };
    if (this.enableLogging) {
      print("[COORD] emit requestStateChanged " + JSON.stringify(payload));
    }
    eventBus.emit(Events.requestStateChanged, payload);
  }

  /**
   * Prints the raw envelope on one line, prefixed so it can be lifted straight
   * out of the log into Assets/AI/fixtures. Every failure becomes a test case
   * instead of a story about something that happened once.
   */
  private dumpFixture(outcome: LessonRequestOutcome, tag: string): void {
    if (!this.dumpFailedResponses) return;
    print("[COORD] FIXTURE|" + slug(outcome.request) + "-" + tag + "|" + outcome.rawEnvelope);
  }

  /** Diagnostics only. */
  public currentState(): string {
    return this.state;
  }

  public currentRequestId(): number {
    return this.requestId;
  }
}

function slug(text: string): string {
  let out = "";
  const lower = (text || "").toLowerCase();
  for (let i = 0; i < lower.length; i++) {
    const ch = lower.charAt(i);
    out += (ch >= "a" && ch <= "z") || (ch >= "0" && ch <= "9") ? ch : "-";
  }
  return out;
}
